// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7mMjup12Y-EwpbxpGIpvL1VRlG5Hm5as',
    appId: '1:393667460067:web:3c357b3ea2ebdc36d43ed6',
    messagingSenderId: '393667460067',
    projectId: 'glyconapp',
    authDomain: 'glyconapp.firebaseapp.com',
    storageBucket: 'glyconapp.appspot.com',
    measurementId: 'G-K714BCHFTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGjbOdmkQduXtfumZUmM0InYYnUV4HNCg',
    appId: '1:393667460067:android:187efec655090b4fd43ed6',
    messagingSenderId: '393667460067',
    projectId: 'glyconapp',
    storageBucket: 'glyconapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8laro6g4fi5rxqYhED-dMRuUAv8kh03I',
    appId: '1:393667460067:ios:88b8c7b3d4d01a98d43ed6',
    messagingSenderId: '393667460067',
    projectId: 'glyconapp',
    storageBucket: 'glyconapp.appspot.com',
    iosBundleId: 'com.example.glyconApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8laro6g4fi5rxqYhED-dMRuUAv8kh03I',
    appId: '1:393667460067:ios:09396893792dcb8fd43ed6',
    messagingSenderId: '393667460067',
    projectId: 'glyconapp',
    storageBucket: 'glyconapp.appspot.com',
    iosBundleId: 'com.example.glyconApp.RunnerTests',
  );
}
